"resource/ui/disguise_menu/spy_blue.res"
{
	"ItemNameLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"ItemName"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"45"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Class_Name_Spy"
		"textAlignment"	"Center"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ClassIcon"	
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"ClassIcon"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"45"
		"tall"			"90"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"	
		"icon"			"hud_menu_scout_blu"
	}
		
	"NumberBg"	
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"NumberBg"
		"xpos"			"23"
		"ypos"			"72"
		"zpos"			"0"
		"wide"			"15"
		"tall"			"15"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"icon"			"ico_key_blank"
		"iconColor"		"255 255 255 255"
	}

	"NumberLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel"
		"font"			"hudfontsmallestbold"
		"fgcolor"		"tandarker"
		"xpos"			"23"
		"ypos"			"71"
		"zpos"			"0"
		"wide"			"15"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"9"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
	}
	"NewNumberLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"NewNumberLabel"
		"font"			"hudfontsmallestbold"
		"fgcolor"		"tandarker"
		"xpos"			"23"
		"ypos"			"71"
		"zpos"			"0"
		"wide"			"15"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"9"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
	}
	
	"NewNumberLabel12"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"NewNumberLabel12"
		"font"			"IconsChar_38"
		"fgcolor_override"		"hudblueteamsolid"
		"xpos"			"13"
		"ypos"			"35"
		"zpos"			"10"
		"wide"			"32"
		"tall"			"32"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"I"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
	}
	"NewNumberLabelSS"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"NewNumberLabelSS"
		"font"			"IconsChar_38"
		"fgcolor"		"0 0 0 100"
		"xpos"			"15"
		"ypos"			"37"
		"zpos"			"10"
		"wide"			"32"
		"tall"			"32"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"I"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
	}
}