"resource/ui/controlpointcountdown.res"
{
	"CapCountdownLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"CapCountdownLabel"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"30"
		"tall"			"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%capturetime%"
		"textAlignment"		"center"
		"fgcolor"		"tanlight"
		"bgcolor"		"235 226 202 0"
	}
	"CapCountdownLabelSS"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"CapCountdownLabelSS"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"30"
		"tall"			"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%capturetime%"
		"textAlignment"		"center"
		"fgcolor"		"0 0 0 120"
		"bgcolor"		"235 226 202 0"
	}
}
