"resource/ui/winpanel.res"
{	
	"TeamScoresPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"TeamScoresPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"

		"WhiteBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"WhiteBG"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"-1"
			"Wide"									"2"
			"Tall"									"30"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"PaintBackgroundType"					"0"
			"paintborder"							"1"
			"border"								"Blank"

			"Pin_To_Sibling"						"TopBarAnchor"
		}
		"TopBarAnchor"
		{
			"ControlName"							"Panel"
			"FieldName"								"TopBarAnchor"
			"XPos"									"cs-0.5"
			"YPos"									"0"
			"Wide"									"2"
			"Tall"									"15"
			"Visible"								"0"
			"Enabled"								"0"
			"Alpha"									"0"
			"ProportionalToParent"					"1"
		}
		"BlueBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"BlueBG"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"2"
			"Wide"									"p0.498"
			"Tall"									"30"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"border"								"MainMenuBGBorder"

			"Pin_To_Sibling"						"WhiteBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
		}
		"BehindBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"BehindBG"
			"XPos"									"2"
			"YPos"									"5"
			"ZPos"									"-1"
			"Wide"									"f5"
			"Tall"									"22"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"border"								"MainMenuBGBorder"
		}
		"BlueBG_2"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"BlueBG_2"
			"XPos"									"3"
			"YPos"									"-30"
			"ZPos"									"3"
			"Wide"									"p0.4925"
			"Tall"									"10"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"border"								"TFFatLineBorderBlueBG"
			"alpha"									"150"

			"Pin_To_Sibling"						"WhiteBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
		}
		"RedBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"RedBG"
			"XPos"									"-1"
			"YPos"									"0"
			"ZPos"									"2"
			"Wide"									"p0.498"
			"Tall"									"30"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"border"								"MainMenuBGBorder"

			"Pin_To_Sibling"						"WhiteBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}
		"RedBG_2"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"RedBG_2"
			"XPos"									"2"
			"YPos"									"-30"
			"ZPos"									"3"
			"Wide"									"p0.4925"
			"Tall"									"10"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"PaintBackground"						"0"
			"border"								"TFFatLineBorderRedBG"
			"alpha"									"150"

			"Pin_To_Sibling"						"WhiteBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}
		
		"ShadedBar"
		{
		"ControlName"								"EditablePanel"
		"FieldName"									"ShadedBar"
		"XPos"										"-5"
		"YPos"										"rs1+3"
		"ZPos"										"2"
		"Wide"										"f-10"
		"Tall"										"30"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"PaintBackground"							"0"
		"border"									"blank"
		}

		"BlueScoreBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"BlueScoreBG"
			"xpos"			"9999"
			"ypos"			"15"
			"wide"			"135"
			"tall"			"40"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			
			"border"		"MainMenuBGBorder"
		}
		"RedScoreBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"RedScoreBG"
			"xpos"			"9999"
			"ypos"			"15"
			"wide"			"135"
			"tall"			"40"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"

			"border"		"MainMenuBGBorder"
		}
		"BlueTeamLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabel"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"-8"
			"ypos"			"10"
			"zpos"			"10"
			"wide"			"100"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"hudoffwhite"

			"Pin_To_Sibling"						"BlueBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
		}	
		"BlueTeamLabelSS"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabelSS"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"-10"
			"ypos"			"8"
			"zpos"			"10"
			"wide"			"100"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"0 0 0 100"

			"Pin_To_Sibling"						"BlueBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
		}							
		"BlueTeamScore"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScore"
			"fgcolor"		"hudblueteamsolid"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"XPos"									"-8"
			"YPos"									"3"
			"ZPos"									"5"
			"Wide"									"100"
			"Tall"									"35"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"HudFontMediumBold"
			"autoResize"	"0"
			"pinCorner"		"0"

			"Pin_To_Sibling"						"BlueBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}
		"BlueTeamScoreDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScoreDropshadow"
			"fgcolor"		"0 0 0 100"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"XPos"									"-6"
			"YPos"									"1"
			"ZPos"									"5"
			"Wide"									"100"
			"Tall"									"35"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"HudFontMediumBold"
			"autoResize"	"0"
			"pinCorner"		"0"

			"Pin_To_Sibling"						"BlueBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}
		"BlueLeaderAvatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"BlueLeaderAvatar"
			"xpos"			"61"
			"ypos"			"14"
			"zpos"			"5"
			"wide"			"40"
			"tall"			"40"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleImage"	"1"	
			"color_outline"	"52 48 45 255"
		}
		"BlueLeaderAvatarBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"BlueLeaderAvatarBG"
			"xpos"			"59"
			"ypos"			"12"
			"zpos"			"4"
			"wide"			"44"
			"tall"			"44"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"bgcolor_override"	"117 107 94 255"
		}									
		"RedTeamLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabel"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"-7"
			"ypos"			"10"
			"zpos"			"102"
			"wide"			"100"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"hudoffwhite"
			
			"Pin_To_Sibling"						"RedBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}		
		
		"RedTeamLabelSS"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabelSS"
			"font"			"HudFontMediumSmallBold"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"-5"
			"ypos"			"8"
			"zpos"			"99"
			"wide"			"100"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"0 0 0 100"
			
			"Pin_To_Sibling"						"RedBG"
			"Pin_Corner_To_Sibling"					"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"					"PIN_TOPRIGHT"
		}	
		
		"TeamFrame2R"
		{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"TeamFrame2R"
		"xpos"			"292"
		"ypos"			"78"
		"zpos"			"-1"
		"wide"				"130"
		"tall"				"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/color_panel_blu"
		"scaleImage"		"1"
		"alpha" "200"
		
		"src_corner_height"		"22"				// pixels inside the image
		"src_corner_width"		"22"
			
		"draw_corner_width"		"5"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"5"	
		}		
		
		"TeamFrame2BB"
		{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"TeamFrame2BB"
		"xpos"			"159"
		"ypos"			"78"
		"zpos"			"-1"
		"wide"				"130"
		"tall"				"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/color_panel_red"
		"scaleImage"		"1"
		"alpha" "200"
		
		"src_corner_height"		"22"				// pixels inside the image
		"src_corner_width"		"22"
			
		"draw_corner_width"		"5"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"5"	
		}			
		
		"RedTeamScore"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"RedTeamScore"
			"XPos"									"-9"
			"YPos"									"3"
			"ZPos"									"5"
			"Wide"									"100"
			"Tall"									"35"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"HudFontMediumBold"
			"LabelText"								"%redteamscore%"
			"TextAlignment"							"west"
			"FGColor"								"hudredteamsolid"

			"Pin_To_Sibling"						"RedBG"
		}
		"RedTeamScoreDropshadow"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScoreDropshadow"
			"XPos"									"-11"
			"YPos"									"1"
			"ZPos"									"4"
			"Wide"									"100"
			"Tall"									"35"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"HudFontMediumBold"
			"LabelText"								"%redteamscore%"
			"TextAlignment"							"west"
			"FGColor"								"0 0 0 100"

			"Pin_To_Sibling"						"RedBG"
		}
		"RedLeaderAvatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"RedLeaderAvatar"
			"xpos"			"9999"
			"ypos"			"9999"
			"zpos"			"5"
			"wide"			"40"
			"tall"			"40"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleImage"	"1"	
			"color_outline"	"52 48 45 255"
		}
		"RedLeaderAvatarBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"RedLeaderAvatarBG"
			"xpos"			"9999"
			"ypos"			"9999"
			"zpos"			"4"
			"wide"			"44"
			"tall"			"44"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"bgcolor_override"	"117 107 94 255"
		}
	}

	"WinPanelBGBorder"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"WinPanelBGBorder"
		"xpos"			"9999"
		"ypos"			"70"
		"zpos"			"0"
		"wide"			"p0.94"
		"tall"			"185"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"		"1"	
		"border"		"MainMenuBGBorder"
		"proportionaltoparent"	"1"
	}

	"BGBorder2"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"BGBorder2"
		"xpos"			"1"
		"ypos"			"451"
		"zpos"			"0"
		"Wide"									"f2"
		"Tall"									"30"
		"visible"		"1"
		"enabled"		"1"	
		"border"		"MainMenuBGBorder"
		"proportionaltoparent"	"1"
	}
	"BGBorder2_3"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"BGBorder2_3"
		"xpos"			"1"
		"ypos"			"429"
		"zpos"			"-1"
		"Wide"									"f2"
		"Tall"									"30"
		"visible"		"1"
		"enabled"		"1"	
		"border"		"MainMenuBGBorder"
		"proportionaltoparent"	"1"
	}
	"WinningTeamLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"WinningTeamLabel"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"-10"
		"ypos"			"-3"
		"zpos"			"1"
		"wide"			"268"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"WEST"
		"dulltext"		"0"
		"brighttext"		"0"
		"FGColor"		"hudoffwhite"
		
			"Pin_To_Sibling"						"BGBorder2"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
	}
	"WinningTeamLabelDropshadow"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"WinningTeamLabelDropshadow"
		"font"			"HudFontMediumSmallBold"
		"xpos"			"-12"
		"ypos"			"-5"
		"zpos"			"1"
		"wide"			"268"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"WEST"
		"dulltext"		"0"
		"brighttext"		"0"
		"FGColor"		"0 0 0 100"
		
			"Pin_To_Sibling"						"BGBorder2"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
	}
	"AdvancingTeamLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"AdvancingTeamLabel"
		"font"			"ScoreboardMedium"
		"xpos"			"15"
		"ypos"			"67"
		"zpos"			"1"
		"wide"			"268"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"%AdvancingTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"AdvancingTeamLabelDropshadow"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"AdvancingTeamLabelDropshadow"
		"font"			"ScoreboardMedium"
		"fgcolor"		"black"
		"xpos"			"16"
		"ypos"			"73"
		"zpos"			"1"
		"wide"			"268"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"%AdvancingTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"WinReasonLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"WinReasonLabel"
		"font"			"ScoreboardSmall"
		"xpos"			"-10"
		"ypos"			"19"
		"zpos"			"1"
		"wide"			"268"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinReasonLabel%"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"FGColor"		"hudoffwhite"
		
			"Pin_To_Sibling"						"BGBorder2"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
	}
	"DetailsLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"DetailsLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"-9"
		"ypos"			"16"
		"zpos"			"1"
		"wide"			"168"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%DETAILSLabel%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"FGColor"		"hudoffwhite"
		
			"Pin_To_Sibling"						"BGBorder2"
			"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
			"Pin_To_Sibling_Corner"					"PIN_TOPLEFT"
	}
	"ShadedBar"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ShadedBar"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"2"
		"wide"			"268"
		"tall"			"125"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"	
		"fillcolor"		"0 0 0 150"
		"fillcolor_lodef"		"0 0 0 200"
		"PaintBackgroundType"	"0"
	}
	"TopPlayersLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TopPlayerLabel"
		"font"			"FontStoreOriginalPrice"
		"xpos"			"-133"
		"ypos"			"-8"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%TopPlayersLabel%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor"			"HudOffWhite"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"PointsThisRoundLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"PointsThisRoundLabel"
		"font"			"FontStoreOriginalPrice"
		"xpos"			"228"
		"ypos"			"178"
		"zpos"			"3"
		"wide"			"140"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0	"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"#Winpanel_PointsThisRound"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"fgcolor"			"HudOffWhite"
	}
	"HorizontalLine"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"260"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"	
		"fillcolor"		"250 234 201 255"
		"PaintBackgroundType"	"0"
	}
	"Player1Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player1Badge"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"Player1Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player1Avatar"
		"xpos"			"-227"
		"ypos"			"-30"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"255 0 0 255"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player1Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Name"
		"xpos"			"-127"
		"ypos"			"-22"
		"font"		"HudFontSmallest"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player1Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Class"
		"xpos"			"-77 "
		"ypos"			"-31"
		"font"		"ScoreboardVerySmall"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player1Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Score"
		"xpos"			"-190"
		"ypos"			"-27"
		"font"		"HudFontMediumSmallBold"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"102"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player2Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player2Badge"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"Player2Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player2Avatar"
		"xpos"			"-65"
		"ypos"			"-30"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"255 0 0 255"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player2Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Name"
		"xpos"			"35"
		"ypos"			"-22"
		"font"		"HudFontSmallest"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player2Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Class"
		"xpos"			"85"
		"ypos"			"-31"
		"font"		"ScoreboardVerySmall"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player2Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Score"
		"xpos"			"-28"
		"ypos"			"-27"
		"font"		"HudFontMediumSmallBold"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"102"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player3Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"Player3Badge"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"Player3Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player3Avatar"
		"xpos"			"97"
		"ypos"			"-30"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"255 0 0 255"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player3Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Name"
		"xpos"			"197"
		"ypos"			"-22"
		"font"		"HudFontSmallest"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player3Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Class"
		"xpos"			"247"
		"ypos"			"-31"
		"font"		"ScoreboardVerySmall"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"Player3Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Score"
		"xpos"			"134"
		"ypos"			"-27"
		"font"		"HudFontMediumSmallBold"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"102"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}

	// KillStreak
	"KillStreakLeaderLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"KillStreakLeaderLabel"
		"font"			"FontStoreOriginalPrice"
		"xpos"			"9999"
		"ypos"			"230"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Winpanel_KillStreakLeader"
		"textAlignment"	"west"
		"fgcolor_override"	"HudOffWhite"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"KillStreakLeaderLabelColored"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"KillStreakLeaderLabelColored"
		"font"			"FontStoreOriginalPrice"
		"xpos"			"352"
		"ypos"			"-8"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Winpanel_KillStreakLeader"
		"textAlignment"	"west"
		"fgcolor_override"	"HudOffWhite"
		"dulltext"		"0"
		"brighttext"	"0"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"KillStreakMaxCountLabel"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"KillStreakMaxCountLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"9999"
		"ypos"			"195"
		"zpos"			"3"
		"wide"			"140"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Winpanel_KillStreakMaxCount"
		"fgcolor_override"	"HudOffWhite"
		"textAlignment"	"east"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"HorizontalLine2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HorizontalLine2"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"260"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"	
		"fillcolor"		"250 234 201 255"
		"PaintBackgroundType"	"0"
	}
	"KillStreakPlayer1Badge"
	{
		"ControlName"	"CTFBadgePanel"
		"fieldName"		"KillStreakPlayer1Badge"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"3"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"KillStreakPlayer1Avatar"
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"KillStreakPlayer1Avatar"
		"xpos"			"259"
		"ypos"			"-30"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"255 0 0 255"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"KillStreakPlayer1Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Name"
		"xpos"			"359"
		"ypos"			"-22"
		"font"		"HudFontSmallest"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"KillStreakPlayer1Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Class"
		"xpos"			"409"
		"ypos"			"-31"
		"font"		"ScoreboardVerySmall"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		
			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
	"KillStreakPlayer1Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"KillStreakPlayer1Score"
		"xpos"			"296"
		"ypos"			"-27"
		"font"		"HudFontMediumSmallBold"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"102"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"

			"Pin_To_Sibling"						"BGBorder2_3"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_TOP"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_TOP"
	}
}