"resource/ui/huddemomanpipes.res"
{
	"background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"background"
		"xpos"			"12"
		"ypos"			"6"
		"zpos"			"0"
		"wide"			"76"
		"wide_minmode"	"56"
		"tall"			"38"
		"visible"		"0"
		"visible_minmode"	"0"
		"enabled"		"0"		
	}
	
	"ChargeLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabel"
		"xpos"			"0"
		"ypos"			"34"
		"zpos"			"14"
		"wide"				"92"
		"tall"				"15"
		"enabled"				"0"
		"labelText"			" "
		"disabledfgcolor2_override" "0 0 0 220"
		"textAlignment"			"center"
		"font"				"MMenuPlayListDesc"
		"border"			"TFFatLineBorder"
	}
	
	"ChargeMeter"
	{	
			"ControlName"			"ContinuousProgressBar"
			"fieldName"				"ChargeMeter"
			"font"					"Default"
			"xpos"					"7"
			"ypos"					"38"
			"zpos"					"15"
			"wide"					"80"
			"tall"					"7"				
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"textAlignment"			"Left"
			"dulltext"				"0"
			"brighttext"			"0"
	}

	"DemoManFrameCharge"
	{
			"ControlName"		"EditablePanel"
			"fieldName"			"DemoManFrameCharge"
			"xpos"				"19"
			"ypos"				"-1"
			"zpos"				"-1"
			"wide"				"52"
			"tall"				"13"
			"visible"			"0"
			"enabled"			"1"
			"border"			"TFFatLineBorder"
	}

		
	"PipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"PipesPresentPanel"
		"xpos"			"-2"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"9999"
			"ypos"			"16"
			"wide"			"0"
			"tall"			"0"
			"visible"		"0"
			"enabled"		"0"
		}	
		
		"ChargeLabelIcons"
		{
		"ControlName"			"Label"
		"fieldName"				"ChargeLabelIcons"
		"xpos"			"51"
		"ypos"			"0"
		"zpos"			"4"
		"wide"			"118"
		"tall"			"14"
		"enabled"				"0"
		"labelText"			"G"
		"disabledfgcolor2_override" "tanlight"
		"textAlignment"			"west"
		"font"				"Icons_12"
		}
		
		"ChargeLabelIcons_Shadow"
		{
		"ControlName"			"Label"
		"fieldName"				"ChargeLabelIcons_Shadow"
			"xpos"			"52"
			"ypos"			"1"
		"zpos"			"4"
		"wide"			"118"
		"tall"			"14"
		"enabled"				"0"
		"labelText"			"G"
		"disabledfgcolor2_override" "0 0 0 150"
		"textAlignment"			"west"
		"font"				"Icons_12"
		}
		
		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"22"
			"ypos"			"-2"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"HudFontSmallBold"
			"fgcolor" "TanLight"
		}
		
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"23"
			"ypos"			"-1"
			"zpos"			"0"
			"wide"			"35"
			"tall"			"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"HudFontSmallBold"
			"fgcolor" "0 0 0 150"
		}		
		"DemoManFrameChargeBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"			"DemoManFrameChargeBG"
			"xpos"				"18"
			"ypos"				"-1"
			"zpos"				"-20"
			"wide"				"60"
			"tall"				"18"
			"visible"			"1"
			"enabled"			"1"
			"border"			"TFFatLineBorder"
			"alpha" "175"
		}
	}
	
	"NoPipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"NoPipesPresentPanel"
		"xpos"			"9999"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"9999"
			"ypos"			"16"
			"wide"			"0"
			"tall"			"0"
			"visible"		"0"
			"enabled"		"0"
		}

		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"11"
			"ypos"			"35"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"0"
			"textAlignment"	"east"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"HudFontSmallBold"
			"fgcolor" "TanLight"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"12"
			"ypos"			"36"
			"zpos"			"0"
			"wide"			"35"
			"tall"			"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"0"
			"textAlignment"	"east"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"HudFontSmallBold"
			"fgcolor" "0 0 0 150"
		}		
	}				
}
