"resource/ui/hudmediccharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"0"			
	}

	
	"AmmoBGFrame"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"AmmoBGFrame"
		"xpos"				"c85"
		"ypos"				"12"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"35"
		"visible"			"0"
		"enabled"			"1"

		"proportionaltoaparent"	"1"
		"border"			"TFThinLineBorder"
	}
	"HPBGFrame"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"HPBGFrame"
		"xpos"				"c-402"
		"ypos"				"30"
		"zpos"				"0"
		"wide"				"112"
		"tall"				"15"
		"visible"			"1"
		"enabled"			"1"

		"proportionaltoaparent"	"1"
		"border"			"TFFatLineBorder"
	}
	
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"				"41"
		"ypos"				"28"
		"zpos"			"222"
		"wide"			"190"
		"tall"			"20"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_Ubercharge"
		"textAlignment"			"west"
		"font"				"MMenuPlayListDesc"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override"		"0 0 0 220"
	}

	"IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"				"41"
		"ypos"				"34"
		"zpos"				"22"
		"wide"				"100"
		"tall"				"7"		
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_IndividualUbercharges"
		"textAlignment"	"west"
		"font"				"MMenuPlayListDesc"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override"		"0 0 0 220"
	}
	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"				"31"
		"ypos"				"34"
		"zpos"				"22"
		"wide"				"100"
		"tall"				"7"		
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"bgcolor_override" 	"0 0 0 50"
		"fgcolor_override" 	"TanLight"
		"dulltext"		"0"
		"brighttext"	"0"
	}		

	"ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"31"
		"ypos"			"34"
		"zpos"			"2"
		"wide"			"24"
		"tall"			"7"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override" 	"TanLight"
		"bgcolor_override" "0 0 0 50"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"55"
		"ypos"			"34"
		"zpos"			"2"
		"wide"			"24"
		"tall"			"7"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override" 	"TanLight"
		"bgcolor_override" "0 0 0 50"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"79"
		"ypos"			"34"
		"zpos"			"2"
		"wide"			"24"
		"tall"			"7"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override" 	"TanLight"
		"bgcolor_override" "0 0 0 50"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"103"
		"ypos"			"34"
		"zpos"			"2"
		"wide"			"28"
		"tall"			"7"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override" 	"TanLight"
		"bgcolor_override" "0 0 0 50"
	}
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"9999"
		"ypos"			"28"
		"wide"			"16"
		"tall"			"16"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/leaderboard_class_medic"
		"scaleImage"	"1"	
	}	
	
	"HPBGFrame"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"HPBGFrame"
		"xpos"				"-10"
		"ypos"				"97"
		"zpos"				"0"
		"wide"				"1000"
		"tall"				"15"
		"visible"			"1"
		"enabled"			"1"

		"proportionaltoaparent"	"1"
		"border"			"TFThinLineBorder"
	}
	
	"ResistIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"xpos"			"c-100"
		"ypos"			"-65"
		"wide"			"24"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	
	}
	
}
